services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: kd-quiz
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - kdquiz-network


  backend:
    build: .
    restart: always
    depends_on:
      - mysqldb
    environment:
      WAIT_HOSTS: mysqldb:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kd-quiz?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    networks:
      - kdquiz-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"  # Swagger UI를 위한 포트 매핑 (로컬 8081 -> 컨테이너 8080)
    environment:
      API_URL: http://13.124.196.182:8080/swagger-ui/index.html  # API 문서의 URL을 지정합니다.
    networks:
      - kdquiz-network
    volumes:
      - ./swagger-config:/usr/share/nginx/html/swagger-config

networks:
  kdquiz-network:
    driver: bridge

