services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: kd-quiz
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - kdquiz-network


  backend:
    build: .
    restart: always
    depends_on:
      - mysqldb
    environment:
      WAIT_HOSTS: mysqldb:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://kdquiz.c9aakqo22nrx.ap-northeast-2.rds.amazonaws.com/kd-quiz?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    networks:
      - kdquiz-network

networks:
  kdquiz-network:
    driver: bridge

