services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: kd-quiz
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - kdquiz-network


  backend:
    build: .
    restart: always
    depends_on:
      - mysqldb
    environment:
      WAIT_HOSTS: mysqldb:3306
      SPRING_DATASOURCE_URL: "jdbc:mysql://master.c9aakqo22nrx.ap-northeast-2.rds.amazonaws.com/kd-quiz?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    networks:
      - kdquiz-network

networks:
  kdquiz-network:
    driver: bridge

