spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://kdquiz.c9aakqo22nrx.ap-northeast-2.rds.amazonaws.com/kd-quiz?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "master"
    password: "12345678"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always


#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: umdmstjd@gmail.com
#    password: abkq wgdm umen vhcu
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: umdmstjd@gmail.com
    password: abkq wgdm umen vhcu
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
            required: true
jwt:
  refresh:
    secret:
      key: acecdd6ae217517dcdeb8db20e0aa74c6c188680101a95c60b2996a8a1cfd51a2950393e36d8154eed556cc3994c85088aa002788da9aa5e33066bc56cd12d1e
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
Email:
  id: umdmstjd@gmail.com
  pw: abkq wgdm umen vhcu

image:
  upload:
    path: src/main/resources/static/img

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Spring Security 로그 레벨 설정
logging:
  level:
    org.springframework.security: DEBUG




