spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/kd-quiz?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "root"
    password: "dmstjd4522"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always

  data:
    redis:
      port: 6379
      host: localhost

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: umdmstjd@gmail.com
#    password: abkq wgdm umen vhcu
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: umdmstjd@gmail.com
    password: abkq wgdm umen vhcu
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
            required: true
jwt:
  secret:
    key: 251fa760ba39a417b9062865a1afe1bfe6fd53b91d29a0c641cb15c78ee853a9
Email:
  id: umdmstjd@gmail.com
  pw: abkq wgdm umen vhcu


# Spring Security 로그 레벨 설정
logging:
  level:
    org.springframework.security: DEBUG




